# Generated by Django 5.1.2 on 2024-10-17 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_position_alter_list_board_alter_task_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='api.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
