# Generated by Django 5.1.2 on 2024-10-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_list_board_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
